# Generated by Django 4.0.5 on 2022-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
